### ISSUE TITLE
Install Anaraky Remarketing Extension

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/PluginBikes#7]
Hi Liam,

We need you to install the Anaraky Remarketing Extension on Pluginbikes (is the same extension we now have installed on Wholesale & Surya). Just found this resource for it (https://github.com/sreichel/magento-Anaraky-GDRT) or you can check the version we have installed on Wholesale or Surya and search for that.

After you install it let me know as I will do the rest with Google.

Thanks,
Florin

**Comment by jabberdog** [comment]
Hi Florin, yeah I can install it however you have assigned this task to Ben. I'll change it now and install it.

**Comment by Florinnn** [comment]
that's fine. Had the feeling I assigned it to you.

**Comment by jabberdog** [comment]
Extension has been installed on Plugin Bikes.
